/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aulainterfacevisual;

/**
 *
 * @author Afonso
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu6 = new javax.swing.JMenu();
        btn_abrir_form1 = new javax.swing.JButton();
        btn_abrir_form_combo = new javax.swing.JButton();
        btn_abrir_form_tabela_produto = new javax.swing.JButton();
        btn_abrir_form_login = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        meno1 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        aaaaaaaaa = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        aaa = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Principal");

        btn_abrir_form1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_abrir_form1.setText("Form de Soma");
        btn_abrir_form1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir_form1ActionPerformed(evt);
            }
        });

        btn_abrir_form_combo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_abrir_form_combo.setText("Form de Combos");
        btn_abrir_form_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir_form_comboActionPerformed(evt);
            }
        });

        btn_abrir_form_tabela_produto.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_abrir_form_tabela_produto.setText("Form Tabela Produto");
        btn_abrir_form_tabela_produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir_form_tabela_produtoActionPerformed(evt);
            }
        });

        btn_abrir_form_login.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_abrir_form_login.setText("Form de Login");
        btn_abrir_form_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abrir_form_loginActionPerformed(evt);
            }
        });

        meno1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulainterfacevisual/img/user.png"))); // NOI18N
        meno1.setText("Login");
        meno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meno1ActionPerformed(evt);
            }
        });

        jMenu5.setText("Form Login");
        meno1.add(jMenu5);

        jMenuBar1.add(meno1);

        jMenu2.setText("Tabela Produto");

        jMenu7.setText("Form Tabela Produto");
        jMenu2.add(jMenu7);

        jMenuBar1.add(jMenu2);

        aaaaaaaaa.setText("ComoBox");

        jMenu9.setText("Form Combos");
        aaaaaaaaa.add(jMenu9);

        jMenuBar1.add(aaaaaaaaa);

        aaa.setText("Soma");

        jMenu4.setText("Form Soma");
        aaa.add(jMenu4);

        jMenuBar1.add(aaa);

        jMenu10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aulainterfacevisual/img/information.png"))); // NOI18N
        jMenu10.setText("Sobre");
        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 238, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_abrir_form1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abrir_form_login)
                    .addComponent(btn_abrir_form_tabela_produto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abrir_form_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_abrir_form1)
                .addGap(29, 29, 29)
                .addComponent(btn_abrir_form_combo)
                .addGap(27, 27, 27)
                .addComponent(btn_abrir_form_login)
                .addGap(31, 31, 31)
                .addComponent(btn_abrir_form_tabela_produto)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_abrir_form1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir_form1ActionPerformed
        // TODO add your handling code here:
        Form1 f1 = new Form1();
        f1.setVisible(true);
    }//GEN-LAST:event_btn_abrir_form1ActionPerformed

    private void btn_abrir_form_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir_form_comboActionPerformed
        // TODO add your handling code here:
        FormCombo fc = new FormCombo();
        fc.setVisible(true);
    }//GEN-LAST:event_btn_abrir_form_comboActionPerformed

    private void btn_abrir_form_tabela_produtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir_form_tabela_produtoActionPerformed
        // TODO add your handling code here:
        cadastroProdutos ftp = new cadastroProdutos ();
        ftp.setVisible(true);
    }//GEN-LAST:event_btn_abrir_form_tabela_produtoActionPerformed

    private void btn_abrir_form_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abrir_form_loginActionPerformed
        // TODO add your handling code here:
        Login ftp = new Login ();
        ftp.setVisible(true);
    }//GEN-LAST:event_btn_abrir_form_loginActionPerformed

    private void meno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meno1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_meno1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aaa;
    private javax.swing.JMenu aaaaaaaaa;
    private javax.swing.JButton btn_abrir_form1;
    private javax.swing.JButton btn_abrir_form_combo;
    private javax.swing.JButton btn_abrir_form_login;
    private javax.swing.JButton btn_abrir_form_tabela_produto;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu meno1;
    // End of variables declaration//GEN-END:variables
}
